// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative service.proto
syntax = "proto3";
package src.internal.protobuf.protobuf;

option go_package = ".;protobuf";

service RPCService {
  rpc OpenStream (stream Message) returns (stream Message) {}
}

message Message {
  oneof message_type {
    Handshake handshake = 1; // 握手
    Farewell farewell = 2; // 告别
    Batch batch = 3;  // 多条消息
  }

  message Handshake {
    string address = 1;
  }

  message Farewell {
    string address = 1;
  }
  
  message Batch {
    repeated BatchEntry entries = 1;
  }

  message BatchEntry {
    string sender_addr = 1;
    string sender_path = 2;
    string receiver_addr = 3;
    string receiver_path = 4;
    string agent_addr = 5;
    string agent_path = 6;
    string type_name = 7;
    bytes message = 8;
    int32 priority = 9;
  }
}
