// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: service.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*Message_Handshake_
	//	*Message_Farewell_
	//	*Message_Batch_
	MessageType   isMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageType() isMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *Message) GetHandshake() *Message_Handshake {
	if x != nil {
		if x, ok := x.MessageType.(*Message_Handshake_); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Message) GetFarewell() *Message_Farewell {
	if x != nil {
		if x, ok := x.MessageType.(*Message_Farewell_); ok {
			return x.Farewell
		}
	}
	return nil
}

func (x *Message) GetBatch() *Message_Batch {
	if x != nil {
		if x, ok := x.MessageType.(*Message_Batch_); ok {
			return x.Batch
		}
	}
	return nil
}

type isMessage_MessageType interface {
	isMessage_MessageType()
}

type Message_Handshake_ struct {
	Handshake *Message_Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"` // 握手
}

type Message_Farewell_ struct {
	Farewell *Message_Farewell `protobuf:"bytes,2,opt,name=farewell,proto3,oneof"` // 告别
}

type Message_Batch_ struct {
	Batch *Message_Batch `protobuf:"bytes,3,opt,name=batch,proto3,oneof"` // 多条消息
}

func (*Message_Handshake_) isMessage_MessageType() {}

func (*Message_Farewell_) isMessage_MessageType() {}

func (*Message_Batch_) isMessage_MessageType() {}

type Message_Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Handshake) Reset() {
	*x = Message_Handshake{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Handshake) ProtoMessage() {}

func (x *Message_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Handshake.ProtoReflect.Descriptor instead.
func (*Message_Handshake) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Handshake) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Message_Farewell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Farewell) Reset() {
	*x = Message_Farewell{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Farewell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Farewell) ProtoMessage() {}

func (x *Message_Farewell) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Farewell.ProtoReflect.Descriptor instead.
func (*Message_Farewell) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_Farewell) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Message_Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Message_BatchEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Batch) Reset() {
	*x = Message_Batch{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Batch) ProtoMessage() {}

func (x *Message_Batch) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Batch.ProtoReflect.Descriptor instead.
func (*Message_Batch) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Message_Batch) GetEntries() []*Message_BatchEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Message_BatchEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderAddr    string                 `protobuf:"bytes,1,opt,name=sender_addr,json=senderAddr,proto3" json:"sender_addr,omitempty"`
	SenderPath    string                 `protobuf:"bytes,2,opt,name=sender_path,json=senderPath,proto3" json:"sender_path,omitempty"`
	ReceiverAddr  string                 `protobuf:"bytes,3,opt,name=receiver_addr,json=receiverAddr,proto3" json:"receiver_addr,omitempty"`
	ReceiverPath  string                 `protobuf:"bytes,4,opt,name=receiver_path,json=receiverPath,proto3" json:"receiver_path,omitempty"`
	AgentAddr     string                 `protobuf:"bytes,5,opt,name=agent_addr,json=agentAddr,proto3" json:"agent_addr,omitempty"`
	AgentPath     string                 `protobuf:"bytes,6,opt,name=agent_path,json=agentPath,proto3" json:"agent_path,omitempty"`
	TypeName      string                 `protobuf:"bytes,7,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Message       []byte                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Priority      int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BatchEntry) Reset() {
	*x = Message_BatchEntry{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BatchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BatchEntry) ProtoMessage() {}

func (x *Message_BatchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BatchEntry.ProtoReflect.Descriptor instead.
func (*Message_BatchEntry) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Message_BatchEntry) GetSenderAddr() string {
	if x != nil {
		return x.SenderAddr
	}
	return ""
}

func (x *Message_BatchEntry) GetSenderPath() string {
	if x != nil {
		return x.SenderPath
	}
	return ""
}

func (x *Message_BatchEntry) GetReceiverAddr() string {
	if x != nil {
		return x.ReceiverAddr
	}
	return ""
}

func (x *Message_BatchEntry) GetReceiverPath() string {
	if x != nil {
		return x.ReceiverPath
	}
	return ""
}

func (x *Message_BatchEntry) GetAgentAddr() string {
	if x != nil {
		return x.AgentAddr
	}
	return ""
}

func (x *Message_BatchEntry) GetAgentPath() string {
	if x != nil {
		return x.AgentPath
	}
	return ""
}

func (x *Message_BatchEntry) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *Message_BatchEntry) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Message_BatchEntry) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x1esrc.internal.protobuf.protobuf\"\xd3\x05\n" +
	"\aMessage\x12Q\n" +
	"\thandshake\x18\x01 \x01(\v21.src.internal.protobuf.protobuf.Message.HandshakeH\x00R\thandshake\x12N\n" +
	"\bfarewell\x18\x02 \x01(\v20.src.internal.protobuf.protobuf.Message.FarewellH\x00R\bfarewell\x12E\n" +
	"\x05batch\x18\x03 \x01(\v2-.src.internal.protobuf.protobuf.Message.BatchH\x00R\x05batch\x1a%\n" +
	"\tHandshake\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x1a$\n" +
	"\bFarewell\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x1aU\n" +
	"\x05Batch\x12L\n" +
	"\aentries\x18\x01 \x03(\v22.src.internal.protobuf.protobuf.Message.BatchEntryR\aentries\x1a\xa9\x02\n" +
	"\n" +
	"BatchEntry\x12\x1f\n" +
	"\vsender_addr\x18\x01 \x01(\tR\n" +
	"senderAddr\x12\x1f\n" +
	"\vsender_path\x18\x02 \x01(\tR\n" +
	"senderPath\x12#\n" +
	"\rreceiver_addr\x18\x03 \x01(\tR\freceiverAddr\x12#\n" +
	"\rreceiver_path\x18\x04 \x01(\tR\freceiverPath\x12\x1d\n" +
	"\n" +
	"agent_addr\x18\x05 \x01(\tR\tagentAddr\x12\x1d\n" +
	"\n" +
	"agent_path\x18\x06 \x01(\tR\tagentPath\x12\x1b\n" +
	"\ttype_name\x18\a \x01(\tR\btypeName\x12\x18\n" +
	"\amessage\x18\b \x01(\fR\amessage\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriorityB\x0e\n" +
	"\fmessage_type2r\n" +
	"\n" +
	"RPCService\x12d\n" +
	"\n" +
	"OpenStream\x12'.src.internal.protobuf.protobuf.Message\x1a'.src.internal.protobuf.protobuf.Message\"\x00(\x010\x01B\fZ\n" +
	".;protobufb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_service_proto_goTypes = []any{
	(*Message)(nil),            // 0: src.internal.protobuf.protobuf.Message
	(*Message_Handshake)(nil),  // 1: src.internal.protobuf.protobuf.Message.Handshake
	(*Message_Farewell)(nil),   // 2: src.internal.protobuf.protobuf.Message.Farewell
	(*Message_Batch)(nil),      // 3: src.internal.protobuf.protobuf.Message.Batch
	(*Message_BatchEntry)(nil), // 4: src.internal.protobuf.protobuf.Message.BatchEntry
}
var file_service_proto_depIdxs = []int32{
	1, // 0: src.internal.protobuf.protobuf.Message.handshake:type_name -> src.internal.protobuf.protobuf.Message.Handshake
	2, // 1: src.internal.protobuf.protobuf.Message.farewell:type_name -> src.internal.protobuf.protobuf.Message.Farewell
	3, // 2: src.internal.protobuf.protobuf.Message.batch:type_name -> src.internal.protobuf.protobuf.Message.Batch
	4, // 3: src.internal.protobuf.protobuf.Message.Batch.entries:type_name -> src.internal.protobuf.protobuf.Message.BatchEntry
	0, // 4: src.internal.protobuf.protobuf.RPCService.OpenStream:input_type -> src.internal.protobuf.protobuf.Message
	0, // 5: src.internal.protobuf.protobuf.RPCService.OpenStream:output_type -> src.internal.protobuf.protobuf.Message
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Handshake_)(nil),
		(*Message_Farewell_)(nil),
		(*Message_Batch_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
